# Generated by Django 5.2.1 on 2025-05-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('cover_image', models.ImageField(upload_to='cover_images/')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
