# Generated by Django 5.2.1 on 2025-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
