# Generated by Django 5.2.1 on 2025-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_artist_alter_song_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
